### PR TITLE
Staging - Facebook Login - Settings Page

### PR DESCRIPTION
**Pull request by hudovisk**
@azb @henrysg456 @baniyapratik @malakimand @Frickes92 
Hey guys, So I implemented login with facebook and a settings page where you can connect with facebook, change your profile pic and reset your password.

The problem is that these features require some keys and environment setup that would be easier to setup all in the AWS instance.

So to test this you have to access it here: http://ec2-54-186-114-57.us-west-2.compute.amazonaws.com/

Can you guys test this so later I can merge into master?

### CODE REVIEW

**Comment by henrysg456** [comment]
I got this error when I tried to connect to facebook: "App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions."

Uploading profile picture was fine.

**Comment by hudovisk** [comment]
I changed the configuration of the app to public now, can you see if you get the same error again?

**Comment by henrysg456** [comment]
https://gyazo.com/00f65b3870439188ba457c8ef5a25b2c

This is after I connected to Facebook, I don't know what to look for but no error this time. :)

**Comment by hudovisk** [comment]
You should look in your profile page and see if now there is a facebook button that links to your profile in facebook.

**Pull request merged**
