### PR TITLE
Post A Service Backend

### PR DESCRIPTION
**Pull request by henrysg456**
@hudovisk I need help with linking current user (which is user posting a service) to employer variable. Also, how will we deal with tags (array of strings)? My first time writing this so let me know what's wrong. Thank you!

### CODE REVIEW

**Comment by hudovisk** [comment]
@henrysg456, you are  almost there. Remember that you need to redirect all request that have the /api url to your controller, or it will never be called. You can see [here](https://github.com/hudovisk/libra-app/blob/post_job_backend/routes.js#L5) how I did it with the user controller. For example you can add this line after that one:

``` JavaScript
app.use('/api', require('./api/services/service-router')(requireSession));
```

Notice that I don't pass the passport framework because the service-controller doesn't need to create the session for the user, it only needs to verify it have a current valid session.

You can see [here](https://github.com/hudovisk/libra-app/blob/post_job_backend/api/users/user-router.js#L5) that I export a function from user-router and that function return the router object configured with user url routes.

I did that because the `require('path/file')` can be interpreted as that `module.exports` object for that file. So when I write `require('./api/services/service-router')(requireSession))` it is basically calling that exported function and passing the requireSession function as parameter so the service-router file can use it. 

So in service-router you will have to export a function that receives whatever dependencies you passed through `require` and return a configured router object.

Also, make sure you run `grunt jshint` to fix possibly syntax errors and comply to the coding standard of JavaScript.

There is also other things that you have to do in the controller. But for now I would suggest you to print a message with `console.log` whenever you receive a get request in /api/services/. 

After you get that I can guide you trough actually using mongoose to query the database.

**Comment by henrysg456** [comment]
@hudovisk I have updated and tested the backend for posting and retrieving all services. Please check it out and let me know if I miss anything.

**Comment by hudovisk** [comment]
Looks good. Just some minor things, once you fix those I can merge it :+1:

**Comment by henrysg456** [comment]
Added the minor changes.

**Pull request merged**
