### PR TITLE
Justin bidding

### PR DESCRIPTION
**Pull request by henrysg456**
@hudovisk Create bidding for applicant is tested, but can you help me with the view-all-biddings of a service? It does return status 200 but no data was showed on postman.

### CODE REVIEW

**Comment by hudovisk** [comment]
Np, I will take a look at this tomorrow..

**Comment by hudovisk** [comment]
This should fix it, can you test again to make sure it works?

**Comment by henrysg456** [comment]
Thanks Hudo, it works perfectly. Some how I tried to push but got this error: https://gyazo.com/1082eae9f5bf3ef0d2aa0cf4566c4984
Can ya merge it to master and close this? I'll continue on other funcs and request another pull later when I complete them.

**Comment by hudovisk** [comment]
Np, I think you just forgot to do git pull to get my last commit.

**Pull request merged**
