### PR TITLE
Initial work on the landing page

### PR DESCRIPTION
**Pull request by hudovisk**
@henrysg456 check this out

### CODE REVIEW

**Comment by hudovisk** [comment]
Hey @azb I think we are pretty much done with the landing page, at least for now that we don't have the jobs part done yet to integrate with the carousel. Can you check it ? If your are ok with it I can merge it to master branch.

 I couldn't get the search field centered in the navbar, my css skills are not good enough :confused:. I will create another branch for the dashboard and then we can discuss more about it there.

**Comment by breathOfTech** [comment]
Hey Hudo,

I can redo-all the CSS customization. I have some experience on the UI
part.

-Pratik

**Comment by henrysg456** [comment]
I will try to get the "post job" back-end done tomorrow then you can test it out. Landing page looks good for me.
Justin 

```
On Monday, March 7, 2016 2:11 PM, Hudo <notifications@github.com> wrote:
```

 Hey @azb I think we are pretty much done with the landing page, at least for now that we don't have the jobs part done yet to integrate with the carousel. Can you check it ? If your are ok with it I can merge it to master branch.I couldn't get the search field centered in the navbar, my css skills are not good enough . I will create another branch for the dashboard and then we can discuss more about it there.—

**Comment by hudovisk** [comment]
Great guys, I will merge it and then and create the dashboard branch.

**Pull request merged**
